apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: foodflow
type: Opaque
data:
  jwt-secret: ZGEzZWY2NjcwYWVjY2M1NWUzZjFiYjYyODNkMzJhY2UwM2VhYjRkMjBjMjUxZTlhOGEwYThmYzRlMWM0YzFhYQ==
