scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'api-gateway'

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8086' ]
        labels:
          application: 'delivery-service'

  - job_name: 'identity-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8087' ]
        labels:
          application: 'identity-service'

  - job_name: 'media-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]
        labels:
          application: 'media-service'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'order-service'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]
        labels:
          application: 'payment-service'

  - job_name: 'restaurant-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: 'restaurant-service'