apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
type: Opaque
stringData:
  DB_USERNAME: auth_db
  DB_PASSWORD: admin@123
data:
  jwt-secret: ZGEzZWY2NjcwYWVjY2M1NWUzZjFiYjYyODNkMzJhY2UwM2VhYjRkMjBjMjUxZTlhOGEwYThmYzRlMWM0YzFhYQ==
